{% set version = "1.30.2" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 72753820246a7d8486e8b385353e3bbf769abfceec2e850fa527a288b084ff7a

build:
  number: 0
  noarch: python 
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  license_file: LICENSE
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
