{% set version = "1.26" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 26116545d6ea12d9ea567e38fa440930f2ae79cd72e4633b8302e93d9d7af887

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
