{% set version = "1.24" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: b6855483d95a03b6aee358363684cd38a3a670240da5bc6da4253079cb07b8df

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
