{% set version = "1.19" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 946b2c837f889971df3575af9dadd8f09bfe48549ebc1b9f6434263b653707ce

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
