{% set version = "1.25" %}

package:
  name: serpent
  version: {{ version }}

source:
  fn: serpent-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/serpent/serpent-{{ version }}.tar.gz
  sha256: 264a028e059c1b557701ae7c567cdab330dbd228ff924489343efcb39bd828a0

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - serpent

about:
  home: https://github.com/irmen/Serpent
  license: MIT
  summary: 'Serialization based on ast.literal_eval'

extra:
  recipe-maintainers:
    - irmen
    - whart222
    - Juanlu001
