# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vHC0md9PXakFqTeCuqHWc8+0SCq4x7gXhPGV+dLpp3jh8ToYXhhNMQoaVFn8kfkudnV9D8mjYg502S5JG5BYBUcYiiO/7GSYadf8zRn+r1WfSHbxZOL0ZcN6FH6DKwW7WhF0FbSThEIWG5jK6vb6mb47w014Ww6VSeQqz3/qUgyGEn3O5s7RdN3yf9TuAqDkxw/Vl51RB+xXZMrjcGPVM0/7BeU8nipTttlybEqZx7sbnCovqplZB0m8TiAfA3rcH88lHyknHJI9rAcecKDXz7Tm1PMxLbLEcHS6O1FO1I0nfgX814dBwVU7I7hqTMtZi42BxaZ7Wlxf9PtvBn50I38O8OLgfkroPSaaNYjPq+5UZpXBzCswYTQAQT4O+5Df3D1kJjqkeLEv/axlq47wP0F4oUgGJF7c0V/UrOKXzU1uLTxtUh308siNvPrfPm6lg9j65QArE3VRhF1+C1pWG5pYXAW7Qa3f0FQyMwWCUCNaOeteTCKtgsDlW/sU7eZtteRLvzB9Gn/4Cm6YXD3IUVjUqIROfKb5NHU9DTeHxVxhYCwe0Adb+bSG7dcsq4wVqToxTrI6J/BgdL3Stwwuat3jAtSClTuomqfGQ1phx1geYxtxZ1xveiDNA8CPFp8Fjhlp1YzLV4ijyd9fyaA2Im1abJTjo28pmbcn+oly2vE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
