travis:
  secure:
    BINSTAR_TOKEN: MjDsgr+7DCc7KftuNMi7vnTCb/iAwh0kCgesoehmZc5ba7qn32PWesQ2beLbyTQPtyGeXZCye63zNEYm9z/gpFSzbVeC8AN6V6hnEbXt/2mMa6opWfGFwy/xk7BvBpQPQK+iWcCc1U8OA+IMw5g8TeKxrNj0nZEKl0DPq0acdUKiaTi9HuPIWdXJLzy9bR+enpu0f/01cL8/lIZS+1hXYGlsGutSgmO011uztkVzI38wNbEZ/Txqr4WleWQCcUs27V6RSe/7ntMRvYfIriRVRebB0Lih/4GZxVlSAsCuyWANGr1U6P094SRqUG1wJUaVTM3c26g8RZL1cRqkfJhNVNAsl7jknTLSMv57rZG/E+2ZSYNuJJ9dxYUcn48xatnljXDGzZxLd7sJTXx8DHvQ1ozfWHMdM0Z7KG+zxNOZwMjNluShBSpVw6dRjrDDSNwu1JyKAvCbYxh9KGo3FEOJEOp9g8XmA7pwP28dcjBgzla4B99VDyQKBSdTV/v1SPHKnM1dP+eQvC+CWtHhk8WFA2loPyQq8ESFRcCK+y+45AojLfBwSM16jdawhqpWwv8SU1LjeVXQxk3XA9cO0cL9rtgrazVRTahFYgkzaiMByiNWu+lZWb0FHU2e/GmTgBzVMY6R0YoxGdKCUy0N6yJ7rFx11CeaY2JL7DyUCh5DNas=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
