travis:
  secure:
    BINSTAR_TOKEN: aLOCV8fRPHoP038PxFqkmc/2hd0X48XGqrjKfx1lweQWX679YlxP3su+Dv3RAlXdGc+kMxcPKI51fLhT4jrilcq9X9OXvhUr6iADMIeMcbcBAw6PWFSZnwKyd31SppirYf2C1ZudwERO9vnAwuRqlvyMDOzHRMz2Y/+1pF1IQ+G3MPKy4eQ5EBLm0LAB3HVNyBJk7T/QTBHJIE++tr/pUEl7zLOvU+i3wsgxjwbcsj7t01llUTEZodoIBt/3zGFJtMsIm8DgGkdbBQ8CBcU8zovSaeUcSfIhV2rdKyrQVkjIYeIFO9vGlFgl9Y+jxGn8Ob9gqk8C0kXel9ZgiLYokvRuZjOctMrEwoaHFtE7Gy+7Y6eJdyXHiBiXcGELiyAXpfYuotcL8ns5yPqeKATU1lhnfWtDVuuUQOMc+f33wamxMnXKFoAosBeDNF8h6BK/wKUzp8QukSk+8HT+rQ06uP0t+t1iIcLC7aL1OSqtTPmU4qT9HrLMnkUB/tRCnTA5rv1pt4E6o+xkM7nI23v8yXyFzFlYYfkw7acMFKujsc2AI+r9/EGMS+iZVMU4ydcyEY5Sks/1CIC8gyowmhiC7fs0CQUXF/YuQuhX+XthD+KVAxtdzwNdvmRMh94vkiOXCMrO89IZROodadYfze9UcFwNu26Mwz5BnPElG89G6Pw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
