travis:
  secure:
    BINSTAR_TOKEN: vHC0md9PXakFqTeCuqHWc8+0SCq4x7gXhPGV+dLpp3jh8ToYXhhNMQoaVFn8kfkudnV9D8mjYg502S5JG5BYBUcYiiO/7GSYadf8zRn+r1WfSHbxZOL0ZcN6FH6DKwW7WhF0FbSThEIWG5jK6vb6mb47w014Ww6VSeQqz3/qUgyGEn3O5s7RdN3yf9TuAqDkxw/Vl51RB+xXZMrjcGPVM0/7BeU8nipTttlybEqZx7sbnCovqplZB0m8TiAfA3rcH88lHyknHJI9rAcecKDXz7Tm1PMxLbLEcHS6O1FO1I0nfgX814dBwVU7I7hqTMtZi42BxaZ7Wlxf9PtvBn50I38O8OLgfkroPSaaNYjPq+5UZpXBzCswYTQAQT4O+5Df3D1kJjqkeLEv/axlq47wP0F4oUgGJF7c0V/UrOKXzU1uLTxtUh308siNvPrfPm6lg9j65QArE3VRhF1+C1pWG5pYXAW7Qa3f0FQyMwWCUCNaOeteTCKtgsDlW/sU7eZtteRLvzB9Gn/4Cm6YXD3IUVjUqIROfKb5NHU9DTeHxVxhYCwe0Adb+bSG7dcsq4wVqToxTrI6J/BgdL3Stwwuat3jAtSClTuomqfGQ1phx1geYxtxZ1xveiDNA8CPFp8Fjhlp1YzLV4ijyd9fyaA2Im1abJTjo28pmbcn+oly2vE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
